import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "Yogesh Tumma",
  description: "Generated by create next app",
  icons: "/images/mehsii.jpg",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={inter.className}>
//       <body>{children}</body>
//     </html>
//   )
// }

// layout.js

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <link rel="icon" href="/images/mehsii.jpg" type="image/jpeg" />

        {/* Load the Google Analytics script */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-929GZGYZHM"
          strategy="afterInteractive"
        />
        {/* Initialize Google Analytics */}
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-929GZGYZHM', {
              page_path: window.location.pathname,
            });
          `}
        </Script>
      </head>
      <body>{children}</body>
    </html>
  );
}
