import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import "./globals.css";


export const metadata = {
  title: "Yogesh Tumma",
  description: "Generated by create next app",
  icons: "/images/mehsii.jpg",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  )
}
